# Generated by Django 4.0.1 on 2022-05-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_user_admin_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='students',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
