# Generated by Django 4.0 on 2022-06-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_delete_note_delete_user_remove_students_granted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.teachers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='aud',
            field=models.CharField(choices=[('306', '306'), ('307', '307'), ('308', '308'), ('309', '309'), ('423', '423')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='day',
            field=models.CharField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота')], max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='students',
            name='group',
        ),
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.groups'),
            preserve_default=False,
        ),
    ]
