# Generated by Django 4.0 on 2022-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_groups_teacher_alter_groups_aud_alter_groups_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fio',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='students',
            name='done_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='grant_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='second_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='third_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groups',
            name='day',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='days',
            field=models.CharField(default='', max_length=255),
        ),
    ]
